### PR TITLE
Add set fan speed example

### PR DESCRIPTION
**Pull request by migius**
I added this example because i spent some time to find how to use this service.

### CODE REVIEW

**Comment by edenhaus** [comment]
Thanks but I think is better to add a link to the offical docs, where all vacuum services are described. E.g in your case https://www.home-assistant.io/integrations/vacuum/#service-vacuumset_fan_speed

**Review by edenhaus — CHANGES_REQUESTED** [review]
Thanks but I think is better to add a link to the offical docs, where all vacuum services are described. E.g in your case https://www.home-assistant.io/integrations/vacuum/#service-vacuumset_fan_speed

Can you please add a link to the vacuum docs instead?

**Comment by migius** [comment]
I'm not sure I correctly understood your request, I add a link, is this what you ask me? if not can you explain me again? I'm new to home assistant world, thank you.

**Comment by migius** [comment]
Hi, I also add play sound example

**Comment by edenhaus** [comment]
I will check it by the end of the week

**Comment by edenhaus** [comment]
Thanks for your work :)
Services offered by HA are documented already on their docs, so we only add a link. If in a future version the structure is changed, we don't need to update all examples as we are referring only by this link.

After the review I decided to use a more general approach as we are documenting all commands under `advanced` and a user can use any command.
So in #131 I'm improved the custom command docs and referred to it. Seel https://deebot.readthedocs.io/integrations/home-assistant/events/#deebot_custom_command

**Pull request closed without merging**
